services:
  db:
    image: postgres:16
    container_name: async_job_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  localstack:
    image: localstack/localstack:3.8.0
    container_name: async_job_localstack
    ports:
      - "4566:4566"
    environment:
      - LS_LOG=debug
    volumes:
      - ./localstack_data:/var/lib/localstack
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
  
  web:
    build: .
    container_name: async_job_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - localstack
  
  worker:
    build: .
    container_name: async_job_worker
    command: python worker.py
    env_file:
      - .env
    depends_on:
      - db
      - localstack

volumes:
  postgres_data: